version: '3'
services:
  api:
    restart: always
    build:
      context: app/microservices
      dockerfile: ./Dockerfile
      args:
        MICROSERVICE: api
    ports:
      - '4000:3000'
  authentification:
    restart: always
    build:
      context: ./app/microservices
      dockerfile: ./Dockerfile
      args:
        MICROSERVICE: authentification
  hello:
    build:
      context: ./app/microservices
      dockerfile: ./Dockerfile
      args:
        MICROSERVICE: hello
  user:
    restart: always
    build:
      context: ./app/microservices
      dockerfile: ./Dockerfile
      args:
        MICROSERVICE: user
